apiVersion: batch/v1
kind: Job
metadata:
  name: echo-job
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: echo
        image: busybox
        command: ["fail"]